### PR TITLE
Add back implementation for pydeequ.checks.hasPattern and accompanyin…

### PR DESCRIPTION
**Pull request by poolis**
…g unit tests.  Original PR: https://github.com/awslabs/python-deequ/pull/36.

*Issue #, if available:*
#71 

*Description of changes:*
Adding back in implementation for pydeequ.checks.hasPattern.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by poolis** [comment]
@gucciwang Is there anything further needed on this PR?  Thanks!

**Comment by zhaokaikai666** [comment]
this property **hasPattern$default$2** is not existed in my application. My PySpark Version is 2.4.3

**Review by chenliu0831 — COMMENTED** [review]
@poolis could you rebase on top of latest mainline? CI should run afterwards

**Comment by chenliu0831** [comment]
I merged #66 recently. Closing this for now. Thanks for the contribution!

**Pull request closed without merging**
