### PR TITLE
Support for Spark 3.1

### PR DESCRIPTION
**Pull request by ashwin153**
Deequ supports Spark 3.1 as of 2.0.0-spark-3.1.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ashwin153** [comment]
@gucciwang Can this be merged?

**Comment by gucciwang** [comment]
Please execute pytests locally following the [README dev guide](https://github.com/awslabs/python-deequ#running-tests-locally) and address the issues present. A quick look and I found 4 errors where 3 of them regard the constraint suggestions, and 1 was regarding pandas utils. 

This thread may be relevant from other users who have tried Spark 3.1 
https://github.com/awslabs/python-deequ/issues/70

**Comment by bradthurber** [comment]
Is it fair to say this needs to be resolved for python-deequ to work with AWS Glue 3.0?

**Comment by alfredHerdwatch** [comment]
Same question as @bradthurber  is this merge needed to be able to use the https://mvnrepository.com/artifact/com.amazon.deequ/deequ/2.0.0-spark-3.1 jar file with glue 3.0?

**Comment by mycaule** [comment]
please approve this

**Comment by Tom-Hudson** [comment]
I really would like to get going with Spark 3.1 - very frustrating that this has hung around for so long

**Comment by chenliu0831** [comment]
I will close this in favor of #100  which seems more complete. Would like a few testers on Glue, EMR etc.

**Pull request closed without merging**
