### PR TITLE
upgrade to 3.4 and fix interface changes

### PR DESCRIPTION
**Pull request by anqini**
> Note: Can we create a separate branch for this change to merge into? The changes are only compatible with scala-deequ version `>=2.0.4`  and not backward compatible. It will look fractional if we make it work universally since for the same class both new and old interfaces need to be invoked.

*Issue #, if available:*

https://github.com/awslabs/python-deequ/issues/148

Forward compatibility issue for scala deequ version >=2.0.4. 

*Description of changes:*

Update the invocation code according to the change of the Scala "deequ-2.0.6-spark-3.4" version interfaces

The interface changes include
- Analyzer class 
  - Compliance
  - Histogram
  - MaxLength
  - MinLength
  - Mean
- Check methods
  - hasMaxLength
  - hasMinLength
  - satisfy

Logic change
- prioritize StringColumnProfile over StandardColumnProfile

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by chenliu0831** [comment]
> Note: Can we create a separate branch for this change to merge into? The changes are only compatible with scala-deequ version >=2.0.4 and not backward compatible. It will look fractional if we make it work universally since for the same class both new and old interfaces need to be invoked.

Currently we don't want to maintain separate branch for different version combinations. I agree we shouldn't make the code fractional to achieve the goal and we are working with a long-term plan with changes in Deequ core ideally. I'll share more details around early Jan. 

Let's keep this PR open for more ideas.

**Comment by anqini** [comment]
Thanks for your update. That sounds good.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Chenyang Liu ***@***.***>
发送时间: Thursday, December 14, 2023 11:18:31 PM
收件人: awslabs/python-deequ ***@***.***>
抄送: Angelo Ni ***@***.***>; Author ***@***.***>
主题: Re: [awslabs/python-deequ] upgrade to 3.4 and fix interface changes (PR #178)


Note: Can we create a separate branch for this change to merge into? The changes are only compatible with scala-deequ version >=2.0.4 and not backward compatible. It will look fractional if we make it work universally since for the same class both new and old interfaces need to be invoked.

Currently we don't want to maintain separate branch for different version combinations. I agree we shouldn't make the code fractional to achieve the goal and we are working with a long-term plan with changes in Deequ core ideally. I'll share more details around early Jan.

Let's keep this PR open for more ideas.

―

**Comment by LeandroLTM** [comment]
Hey @anqini @chenliu0831, is there a potential date to merge this PR? Looks like Deequ is already adding [support to Spark 3.5](https://github.com/awslabs/deequ/pull/514)

**Comment by chenliu0831** [comment]
Closing this PR for now - we do not plan to maintain multiple branches and the changes mostly likely have to go to Deequ

**Pull request closed without merging**
