### PR TITLE
chore: upgrade Spark to 3.4, and Deequ to 2.0.5

### PR DESCRIPTION
**Pull request by chenliu0831**
*Issue #, if available:* https://github.com/awslabs/python-deequ/issues/151

*Description of changes:*

Upgrade Spark to 3.4 and Deequ to 2.0.5

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by chenliu0831** [comment]
The test failures are because some new optional parameters were introduced with the new version of Deequ (e.g. the [analyzerOptions](https://github.com/awslabs/deequ/commit/067710be11ad992a3b706006f0c566b1c5796754)). Today the Python land cannot leverage the default parameters in Scala land... so it throws an error. 

If the interface have to be an exact match, the code will bifurcate (since older version of Deequ won't have this parameter) e.g. below fixed the issue for deequ 2.0.5 but broken deequ <2.0.5

```python
-        self._Check = self._Check.hasMaxLength(column, assertion_func, hint)
+        analyzer_options = self._jvm.scala.Option.apply(None)
+        self._Check = self._Check.hasMaxLength(column, assertion_func, hint, analyzer_options)
```

**Comment by chenliu0831** [comment]
We have been busy with re:invent - expect some progress  in Dec.

**Comment by repcaks** [comment]
Hi, is there a potential date for supporting Spark 3.4 ? :)  Is it more December/January or even later ?

**Comment by machadoluiz** [comment]
Hello, @chenliu0831! Is there a expected date for supporting this Spark version?

**Comment by katiesandford** [comment]
Hi is there any update on this please?

**Comment by anqini** [comment]
Hi All, i created a new pull request to accommodate spark 3.4 version and deequ later than 2.0.3. Welcome to take a look.
https://github.com/awslabs/python-deequ/pull/178

**Comment by chenliu0831** [comment]
@anqini thanks so much for looking into this and submit the PR. Unfortunately, we cannot drop the support to older Spark/Deequ version yet. I will take a closer look in #178.  

All - we have discussed with Deequ team and we will be working on a longer term solution including supporting plan for older Spark versions. There's no ETAs yet (some plan in Jan) but good news is we merged the maintainer groups from both repo.  I will be looking into if we can have a safe short term solution in PyDeequ only this weekend.

**Comment by dudumottavasconcelos** [comment]
Hi, @chenliu0831! Any news on this upgrade?

**Comment by MatheusXCH** [comment]
Hello all! Any news on version upgrade?

**Comment by katiesandford** [comment]
Hi. Is there any update on this please?

**Comment by chenliu0831** [comment]
Closing this for now, see my comments in https://github.com/awslabs/python-deequ/issues/192#issuecomment-1972385951 and we can provide updates there

**Pull request closed without merging**
